module "blue" {
  source = "../single-stack"
  color = "blue"

  project = "${var.project}"
  name = "${var.name}"
  environment = "${var.environment}"
  ami = "${var.ami}"
  instance_type = "${var.instance_type}"
  key_name = "${var.key_name}"
  loadbalancers = "${var.loadbalancers}"
  security_group = "${var.security_group}"
  iam_instance_profile = "${var.iam_instance_profile}"
  associate_public_ip_address = "${var.associate_public_ip_address}"
  user_data = "${var.user_data}"
  disksize = "${var.disksize}"
  availability_zones = "${var.availability_zones}"
  subnets = "${var.subnets}"
  max_size = "${var.max_size}"
  min_size = "${var.min_size}"
  desired_capacity = "${var.desired_capacity}"
  health_check_grace_period = "${var.health_check_grace_period}"
}

module "green" {
  source = "../single-stack"
  color = "green"

  project = "${var.project}"
  name = "${var.name}"
  environment = "${var.environment}"
  ami = "${var.ami}"
  instance_type = "${var.instance_type}"
  key_name = "${var.key_name}"
  loadbalancers = "${var.loadbalancers}"
  security_group = "${var.security_group}"
  iam_instance_profile = "${var.iam_instance_profile}"
  associate_public_ip_address = "${var.associate_public_ip_address}"
  user_data = "${var.user_data}"
  disksize = "${var.disksize}"
  availability_zones = "${var.availability_zones}"
  subnets = "${var.subnets}"
  max_size = "${var.max_size}"
  min_size = "${var.min_size}"
  desired_capacity = "${var.desired_capacity}"
  health_check_grace_period = "${var.health_check_grace_period}"
}
